# Generated by Django 4.1.6 on 2023-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(max_length=30, null=True, verbose_name='ваш любимый цвет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='developer',
            field=models.IntegerField(choices=[(1, 'BEKEND'), (2, 'FRONTEND'), (3, 'IOS'), (4, 'ANDROID')], null=True, verbose_name='какой ты разработчик?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ice_cream',
            field=models.IntegerField(choices=[(1, 'YES'), (2, 'NO')], null=True, verbose_name='вы любите мороженое?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lunch',
            field=models.CharField(max_length=100, null=True, verbose_name='что вы кушали сегодня на обед?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mbti_test',
            field=models.IntegerField(choices=[(1, 'INTJ'), (2, 'INTP'), (3, 'ENTJ'), (4, 'ENTP'), (5, 'INFJ'), (6, 'INFP'), (7, 'ENFJ'), (8, 'ENFP'), (9, 'ISTJ'), (10, 'ISFJ'), (11, 'ESTJ'), (12, 'ESFJ'), (13, 'ISTP'), (13, 'ISTP'), (15, 'ESTP'), (16, 'ESFP')], null=True, verbose_name='ваш тип личности'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pepsi_or_cola',
            field=models.IntegerField(choices=[(1, 'PEPSI'), (2, 'COLA')], null=True, verbose_name='выбирайте'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'VIPClient'), (3, 'CLIENT')], verbose_name='Тип пользователя'),
        ),
    ]
