# Generated by Django 4.1.6 on 2023-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoramyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BookParser',
        ),
    ]
